zhortein_datatable_fetch_data:
  path: /zhortein/symfony-toolbox/datatable/{datatableId}/data
  controller: Zhortein\SymfonyToolboxBundle\Controller\DatatableController::fetchData
  requirements:
    datatableId: .+
  options:
    expose: true
zhortein_datatable_export:
  path: /zhortein/symfony-toolbox/datatable/{datatableId}/export/csv
  controller: Zhortein\SymfonyToolboxBundle\Controller\DatatableController::export
  requirements:
    datatableId: .+
  methods: [GET]
  options:
    expose: true