zhortein_datatable_fetch_data:
  path: /zhortein/symfony-toolbox/datatable/{datatableId}/data
  controller: Zhortein\SymfonyToolboxBundle\Controller\DatatableController::fetchData
  requirements:
    datatableId: .+
  methods: [GET, POST, OPTIONS]
  options:
    expose: true
zhortein_datatable_export:
  path: /zhortein/symfony-toolbox/datatable/{datatableId}/export/csv
  controller: Zhortein\SymfonyToolboxBundle\Controller\DatatableController::export
  requirements:
    datatableId: .+
  methods: [GET, POST, OPTIONS]
  options:
    expose: true
zhortein_datatable_filters:
  path: /zhortein/symfony-toolbox/datatable/{datatableId}/filters-info
  controller: Zhortein\SymfonyToolboxBundle\Controller\DatatableController::getFiltersInfo
  requirements:
    datatableId: .+
  methods: [GET, POST, OPTIONS]
  options:
    expose: true